#28 developブランチへのリクエスト時のActionsを修正

diff --git a/.github/workflows/deploy_to_dev.yml b/.github/workflows/deploy_to_dev.yml
--- a/.github/workflows/deploy_to_dev.yml
+++ b/.github/workflows/deploy_to_dev.yml
@@ -6,17 +6,40 @@ on:
       - develop
 
 jobs:
-  deploy:
+  test:
     runs-on: ubuntu-latest
     permissions:
       contents: 'read'
       id-token: 'write'
 
     steps:
+      - name: set up
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.20
+        id: go
       - id: checkout
         name: Checkout repo
         uses: actions/checkout@v2
 
+      - name: Coverage Check
+        id: coverage_check #@FIXME: デプロイの自動化の検証のため、一時的にカバレッジ閾値を変更
+        run: |
+          go test -coverprofile=coverage.out ./...
+          COVERAGE=$(go tool cover -func=coverage.out | grep 'total:' | awk '{ print $3 }' | sed 's/%//g')
+          echo "Coverage: ${COVERAGE}%"
+          if (( $(echo "$COVERAGE < 10.0" | bc -l) )); then
+            echo "Error: coverage is below 10%"
+            exit 1
+          fi
+
+  deploy:
+    runs-on: ubuntu-latest
+    env:
+      TZ: Asia/Tokyo
+    needs: test
+    if: needs.test.outputs.coverage_check == 'true'
+    steps:
       - name: Generate timestamp
         id: timestamp
         run: echo "::set-output name=value::$(date +%Y%m%d-%H%M%S)"
